# Generated by Django 4.2.5 on 2023-09-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_email_profile_social_service_myworkexperience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeadback',
            options={'verbose_name_plural': 'رضایت مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='myworkexperience',
            options={'verbose_name_plural': 'تجربیات'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'سرویس ها'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AlterField(
            model_name='customerfeadback',
            name='start',
            field=models.IntegerField(verbose_name='تعداد ستاره'),
        ),
        migrations.AlterField(
            model_name='service',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account_app.profile', verbose_name='Profile'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/services/', verbose_name='عکس')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='account_app.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
