# Generated by Django 4.2.5 on 2023-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_customerfeadback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
    ]
